name: CD

on:
  push:
    tags: 
      - '*'
      - "!daily-*"

jobs:
  docker-push:
    name: Push to container registry
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build relic
      run: make crypto_setup_gopath
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDP }}
        service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Docker build
      run: |
        make docker-build-flow
        make docker-build-flow-without-netgo
    - name: Docker push
      run: |
        make docker-push-flow
        make docker-push-flow-without-netgo
